### ISSUE TITLE
User log for data entry not accurate

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#280] opened 2016-05-09 16:12 UTC
Yoon of OD Myanmar was uploading a resource as a dataset. Her profile says that she owns no datasets yet she has created one (set to private) which I can view. 

![image](https://cloud.githubusercontent.com/assets/14996905/15119433/33ec62a0-1611-11e6-8b81-932aa28c8cbd.png)

The dataset is listed here: 
https://data.opendevelopmentmekong.net/dataset/myanmar-census-2014?type=dataset

Regardless if the dataset is private or not shouldn't we be able to see a log of a users activity?

**Comment by acorbi** [comment] 2016-05-11 16:56
@prustar you cannot see any dataset on yoon's profile because they are private. Once they are published you will be able to see them. In case you want to see private datasets which need to be reviewed use the links to the organizations:

https://pp-data.opendevelopmentmekong.net/organization/cambodia-organization
https://pp-data.opendevelopmentmekong.net/organization/myanmar-organization
https://pp-data.opendevelopmentmekong.net/organization/mekong-organization
https://pp-data.opendevelopmentmekong.net/organization/vietnam-organization
https://pp-data.opendevelopmentmekong.net/organization/laos-organization
https://pp-data.opendevelopmentmekong.net/organization/thailand-organization

Since this is the *current* expected behaviour, im closing this Issue. If you have any other request related to this, please reopen and comment

**Comment by prustar** [comment] 2016-05-11 17:16
@acorbi thanks for this - the other issue I have is that I'm doing this but I can't immediately see who owns the dataset without going to the show metadata site: https://data.opendevelopmentmekong.net/api/3/action/package_show?id=[xxx]

Is there a way to display the owner of the dataset so I can easily identify them and contact them if there is a problem?

**Comment by acorbi** [comment] 2016-05-11 20:19
@prustar I have opened this Issue https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/278 which would tackle that request. Closing this issue...

**Closed by acorbi** 2016-05-11 20:19 UTC
Labels: bug, question
