### ISSUE TITLE
Multilingual functionality missing in two metadata fields - Process(es) and Source(s)

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#261] opened 2016-02-03 09:28 UTC
For map entries we have noticed that when translating there are two fields which do not have multilingual support, which means that in which ever language the last entry was made is the language that is displayed. In all cases this means that the English text for the fields Process and Source are replaced with the Khmer. 

![ckan_bug_multilingual](https://cloud.githubusercontent.com/assets/14996905/12778065/e9f43020-ca60-11e5-8cc7-9d7b14258272.JPG)

**Comment by acorbi** [comment] 2016-02-03 10:21
This is not a bug, according to the current metadata definition https://wiki.opendevelopmentmekong.net/public:metadata there are certain fields that do not have multilingual support.

**Comment by prustar** [comment] 2016-02-03 12:06
Thanks Alex, so enhancement is better? Can I ask why these were left of ML function? These fields are mandatory so shouldn't they also be available in all languages necessary to be accessible for all users. Unfortunately Samean has to go through them all again to make sure they are corrected.

**Comment by jpeizer1** [comment] 2016-02-03 16:53
@prustar  @acorbi It would make logical sense that all mandatory fields would also require the multi-lingual support, however if that wasn't the case in the original specs for whatever reason it would at this point be an enhancement neccesary for the next version.

Pyrou as these aren't multilingual fields now I'd recommend you _**ADD **_the Khmer to the English already in there and not just replace it. If you just replace it, it means we lose the English information. 

Should we need to change these fields to multilingual later. We'd want the information there in both languages so we could separate it and place the Khmer in the Khmer field and the English in the English field.

**Comment by acorbi** [comment] 2016-02-08 07:33
@prustar @jpeizer1 @Huyeng FYI: The current implementation does not allow mandatory fields to be defined as multilingual, this is a technical restriction the system currently has but can/should be fixed  . 

In my opinion, the criteria for a field to be marked as multilingual would be that it actually is ment to contain multilingual data. there are field types such as Numbers or Addresses that contain information that is not "localizable"

**Comment by prustar** [comment] 2016-02-08 09:28
I just noticed that the topics are also not translated and this is another mandatory field so should be included in this next fix as well.

**Comment by acorbi** [comment] 2016-02-08 10:59
@prustar thanks for raising this, I have created following Issue: https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/263

**Closed** 2016-05-23 16:26 UTC
Labels: enhancement
