### ISSUE TITLE
Entering in Library records being listed as Datasets

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_dataset#267] opened 2016-04-11 09:27 UTC
Not sure if this is a bug or has any significance on the database but while the ODC team have been entering in library records they have been recorded with a _dataset URL instead of the _library_record: 

![image](https://cloud.githubusercontent.com/assets/14996905/14422557/b971b876-ffd7-11e5-8e88-920af009c95d.png)

But when you go into 'manage' it changes to _library_record: 

![image](https://cloud.githubusercontent.com/assets/14996905/14422581/dbab4e16-ffd7-11e5-8c7d-541ea6a87989.png)

Others on are entered and allocated a _library_records URL: 

![image](https://cloud.githubusercontent.com/assets/14996905/14422620/0b8a468c-ffd8-11e5-8a12-2f67b5054053.png)

If it's not a problem then I will close the issue.

**Comment by acorbi** [comment] 2016-04-21 16:06
Hi @prustar this is not a bug.

Datasets are accessible through different paths on the URL, see:

https://data.opendevelopmentmekong.net/dataset/bridging-the-gap-between-conservation-and-community-development-in-post-conflict-cambodia

same as

https://data.opendevelopmentmekong.net/library_record/bridging-the-gap-between-conservation-and-community-development-in-post-conflict-cambodia

same as

https://data.opendevelopmentmekong.net/laws_record/bridging-the-gap-between-conservation-and-community-development-in-post-conflict-cambodia

However the page is always rendered as library record because the **type** field is **library_record**, see https://data.opendevelopmentmekong.net/api/3/action/package_show?id=bridging-the-gap-between-conservation-and-community-development-in-post-conflict-cambodia.

Im closing this

**Closed by acorbi** 2016-04-21 16:06 UTC
Labels: bug, question
